version: '3.5'

services:
  elasticsearch-lab-1:
    container_name: elasticsearch-lab-1
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "cluster.name=elasticsearch-lab-cluster"  #Sets cluster name
      - "node.name=elasticsearch-lab-node-1"      #Sets node name
      - "network.host=0.0.0.0"                    #Sets binding ip to all
      - "xpack.security.enabled=false"            #Disables xpack security
      - "xpack.monitoring.enabled=false"          #Disables xpack monitoring
      - "xpack.watcher.enabled=false"             #Disables xpack watcher
      - "xpack.ml.enabled=false"                  #Disables xpack machine learning
      - "bootstrap.memory_lock=true"              #Disables memory swap
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"        #Sets allocated memory
      - "discovery.type=single-node"
    ulimits:
      memLock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch-lab/unique-node:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet

  carebro:
    container_name: cerebro-lab
    image: lmenezes/cerebro:0.8.1
    ports:
      - "9000:9000"
    external_links:
      - elasticsearch-lab-1:elasticsearch1
    networks:
      - esnet

  kibana:
    container_name: kibana-lab
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - "5601:5601"
    external_links:
      - elasticsearch-lab-1:elasticsearch1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch1:9200

  postgres:
    image: postgres:10.5
    container_name: postgres-1
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
